/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiasGameMonsterRouteImport } from './routes/guias.$game.$monster'
import { Route as GuiasGameMonsterWeaponRouteImport } from './routes/guias.$game.$monster.$weapon'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasGameMonsterRoute = GuiasGameMonsterRouteImport.update({
  id: '/guias/$game/$monster',
  path: '/guias/$game/$monster',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasGameMonsterWeaponRoute = GuiasGameMonsterWeaponRouteImport.update({
  id: '/$weapon',
  path: '/$weapon',
  getParentRoute: () => GuiasGameMonsterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guias/$game/$monster': typeof GuiasGameMonsterRouteWithChildren
  '/guias/$game/$monster/$weapon': typeof GuiasGameMonsterWeaponRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guias/$game/$monster': typeof GuiasGameMonsterRouteWithChildren
  '/guias/$game/$monster/$weapon': typeof GuiasGameMonsterWeaponRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guias/$game/$monster': typeof GuiasGameMonsterRouteWithChildren
  '/guias/$game/$monster/$weapon': typeof GuiasGameMonsterWeaponRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guias/$game/$monster' | '/guias/$game/$monster/$weapon'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guias/$game/$monster' | '/guias/$game/$monster/$weapon'
  id:
    | '__root__'
    | '/'
    | '/guias/$game/$monster'
    | '/guias/$game/$monster/$weapon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiasGameMonsterRoute: typeof GuiasGameMonsterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$game/$monster': {
      id: '/guias/$game/$monster'
      path: '/guias/$game/$monster'
      fullPath: '/guias/$game/$monster'
      preLoaderRoute: typeof GuiasGameMonsterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$game/$monster/$weapon': {
      id: '/guias/$game/$monster/$weapon'
      path: '/$weapon'
      fullPath: '/guias/$game/$monster/$weapon'
      preLoaderRoute: typeof GuiasGameMonsterWeaponRouteImport
      parentRoute: typeof GuiasGameMonsterRoute
    }
  }
}

interface GuiasGameMonsterRouteChildren {
  GuiasGameMonsterWeaponRoute: typeof GuiasGameMonsterWeaponRoute
}

const GuiasGameMonsterRouteChildren: GuiasGameMonsterRouteChildren = {
  GuiasGameMonsterWeaponRoute: GuiasGameMonsterWeaponRoute,
}

const GuiasGameMonsterRouteWithChildren =
  GuiasGameMonsterRoute._addFileChildren(GuiasGameMonsterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiasGameMonsterRoute: GuiasGameMonsterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
